{{- if .Values.persistentVolume.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  {{- if .Values.persistentVolume.storageClass -}}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistentVolume.storageClass }}
  {{ else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
  {{- range $key, $value := .Values.persistentVolume.annotations }}
    {{ $key }}: {{ $value }}
  {{- end }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "fullname" . }}
spec:
  accessModes:
{{- range .Values.persistentVolume.accessModes }}
  - {{ . | quote }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size | quote }}
{{- end -}}
