# Thie file sets up in-cluster service discovery for our app.
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  # We want to listen on the default HTTP port, and send traffic to the port
  # our docker image is acutally listening on (which is defined in
  # deployment.yaml)
  - port: 80
    targetPort: http
  selector:
    app:  {{ template "fullname" . }}
